
INSERT INTO genres (GENRE_NAME)
VALUES ('Комедия');

INSERT INTO genres (GENRE_NAME)
VALUES ('Драма');

INSERT INTO genres (GENRE_NAME)
VALUES ('Мультфильм');

INSERT INTO genres (GENRE_NAME)
VALUES ('Триллер');

INSERT INTO genres (GENRE_NAME)
VALUES ('Документальный');

INSERT INTO genres (GENRE_NAME)
VALUES ('Боевик');

INSERT INTO mpa (RATING_NAME)
VALUES ('G');

INSERT INTO mpa (RATING_NAME)
VALUES ('PG');

INSERT INTO mpa (RATING_NAME)
VALUES ('PG-13');

INSERT INTO mpa (RATING_NAME)
VALUES ('R');

INSERT INTO mpa (RATING_NAME)
VALUES ('NC-17');